import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import RoundButtons from '../components/RoundButton'
import QtyAddCart from '../components/QtyAddCart'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Tiendas - ComeS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Primera web ComeS
        </h1>
        <div>
          <RoundButtons text={'-'} backgroundColor={'var(--secondary)'} size={'30px'} id='reduce' disabled/>
          <QtyAddCart value={0} fontSize={'12px'} />
          <RoundButtons text={'+'} backgroundColor={'var(--secondary)'} size={'30px'} id='increase'/>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>ComeS 2022</p>
      </footer>
    </div>
  )
}
